name: Publish release
on:
  push:
    branches:
      - main
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish release
        run: |
          cat README.md
          dir=$PWD
          echo "> $dir"
          git clone "https://tuanchauict:${{secrets.AUTH}}@github.com/monosketch/demo-alpha-release.git" "../src"
          pwd
          mv -f README.md ../src
          cd ../src
          pwd
          git add README.md
          git status
          git commit -m "Update readme"
          git config user.email "tuanchau@example.com"
          git config user.name "Tuan Chau"
          git push